using Agents.Common.Interfaces;
using Microsoft.Extensions.AI;

namespace Agents.Common;

/// <summary>
/// Represents a language model interface using the LLm client for handling chat-based interactions.
/// This class allows interaction with a language model by sending prompts and receiving responses.
/// </summary>
public class LLm(string model = "llama3") : ILLm
{
    private OllamaChatClient Client => new ("http://localhost:11434/", model);
    private readonly List<ChatMessage> _chatHistory = [];

    /// <summary>
    /// Sends a prompt to the language model and retrieves a response.
    /// The prompt is added to the chat history and the response is generated by the language model client.
    /// </summary>
    /// <param name="prompt">The user input sent to the language model as a string.</param>
    /// <returns>A task representing the asynchronous operation. The result contains the response from the language model as a string, or null if no response is generated.</returns>
    public async Task<string?> SendMessage(string prompt)
    {
        _chatHistory.Add(new ChatMessage(ChatRole.User, prompt));
        var response = "";
        await foreach(var item in Client.GetStreamingResponseAsync(_chatHistory))
        {
            response += item;
        }
        _chatHistory.Add(new ChatMessage(ChatRole.Assistant, response));
        return response;
    }
}